### ISSUE TITLE
How to install this webpanel ?

### ISSUE THREAD

**Issue by nguyenbaodanh** [SourceMod-Store/WebPanel-Core#14]
At first I'm sorry for this noob question ... but How to install this webpanel since I downloaded the WebPanel-Core-master.zip ?

I extracted everything but not sure which one to upload to the webhost ...
Thanks for your help

**Comment by Arrow768** [comment]
You need to have ssh access to the webhost to install the panel.
You also need composer installed

If you have got ssh access, just connect to the host and do the following:
- Run: git clone https://github.com/SourceMod-Store/WebPanel-Core.git
- Run: composer install
- Run: php artisan migrate
- Point the document root to the /public directory
- Rename the .env.example to to .env and enter your settings

**Comment by nguyenbaodanh** [comment]
Thanks. I have ssh access. Currently I've installed a version which I get
from alliedmoder ...
Gstore.1hp-gaming.com
But seem not work for the chatcolors plugin. Can it be caused by webstore
panel?
And do I need to remove this version before install this ?

**Comment by Arrow768** [comment]
The webpanel version you are referring to is hosted here:
https://github.com/SourceMod-Store/store-webpanel

If the chatcolors module is not working when you are using the old webpanel, it wont magically start to work when you use the new webpanel.
The WebPanel is "just" a way to manage the installation of the store plugin.

At the moment you should do a fresh install from scratch (including the database) when switching from the old webpanel to the new one. (Thats one of the reasons why its still a beta version)

I strongly recommend to use the old webpanel for production servers.
