### ISSUE TITLE
Fresh Install issue

### ISSUE THREAD

**Issue by ghost** [SourceMod-Store/WebPanel-Core#18]
I fresh installed package.zip and heading to the public directory gives this:

> Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /home/ostkkbar/public_html/store/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php on line 101

I tried downloading another time and it still gives this same error.

**Comment by Arrow768** [comment]
Verify that you meet the minimum requirements.

**Comment by ghost** [comment]
I got it up and working. But every page I head to in the admin panel, it shows

> Alerts
> An Error has been encountered
> 
> You do not have the permission **WebPanelStoreCategoriesCreate** that is required to perform this action

what could cause this?

**Comment by Arrow768** [comment]
This error means that you dont have the permission that is required to perform the action you wish to perform.

A user needs to be assigned to a group
And a group needs to be assigned permissions

Verify that you are in the admin group and that the admin group has got the permissions assigned.

Also how did you manage to fix the error ?

**Comment by ghost** [comment]
thanks!! I added a row to the webpanel_role_user table and works now. 
I fixed the error by switching my host provider so I don't really know what was the issue still but well.
