### ISSUE TITLE
There is no http://link.link/installer

### ISSUE THREAD

**Issue by gabyfle** [SourceMod-Store/WebPanel-Core#19]
Hello Store webpanel community ! I try to install ur webpanel 2.0 BUT here https://github.com/SourceMod-Store/WebPanel-Core/releases ( the link given in the wiki ) there is no "release.zip".

So, i don't understand this sentence : Go to the Release Page and download the package.zip for the release that you would like to use.
Upload the release.zip to your webserver

This is really wtf. I know that this is not the right place to answer help but in the alliedmodders forums nobody tell me where i can get this.

Thanks a lot in advance,

Gaby 💯

**Comment by Arrow768** [comment]
Just to confirm.
You have replaced the link.link part with the proper link to the webpanel installation ?

**Comment by Arrow768** [comment]
Actually. I just noticed that I used the wrong name filename in the tutorial.
Download the package.zip and upload it to the webspace and unzip it there. (Or unzip it before uploading)

**Comment by lowlevl** [comment]
@Arrow768 I got the same problem, there is no 'installer' file or directory \*-\* !
WTF ?

**Comment by lowlevl** [comment]
And no 'public/installer' file or directory or even 'installer.php'

**Comment by Hackmastr** [comment]
@Thecakeisgit It's different than files, go to http://YOURDOMAIN.com/installer

**Comment by lowlevl** [comment]
I know man -_- Thanks, i got no problem with php and sysadmin.. @Hackmastr It just don't works \*-\*

**Comment by lowlevl** [comment]
It's just i didn't saw any rewrite, anything pointing to that 'installer'..

**Comment by Arrow768** [comment]
There is no installer file or redirect because it's done⁣​ via the Laravel router.
