### ISSUE TITLE
CLI installation does not include the vendor directory

### ISSUE THREAD

**Issue by TheTreek** [SourceMod-Store/WebPanel-Core#21]
The CLI installation did not include the vendor directory for me, I had to download it and upload it via FTP, I don't know if that was on my end or on yours. :/

**Comment by Arrow768** [comment]
Intentional, as the dependencies are downloaded using `php composer.phar install`

**Comment by FFFAS444** [comment]
I used the command  and it's showing me these 2 lines.

Warning: require(/var/www/html/smstore2/bootstrap../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/smstore2/bootstrap/autoload.php on line 17

Fatal error: require(): Failed opening required '/var/www/html/smstore2/bootstrap../vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/smstore2/bootstrap/autoload.php on line 17

I'm using php 7.4.
