### ISSUE TITLE
Webpage won't load?

### ISSUE THREAD

**Issue by TheTreek** [SourceMod-Store/WebPanel-Core#22]
This is the error log:

[Sun Apr 16 17:49:59.609026 2017] [:error] [pid 26892] [client 73.228.114.134:54228] PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/var/www/shop/WebPanel-Core/storage/logs/laravel-2017-04-16.log" could not be opened: failed to open stream: Permission denied' in /var/www/shop/WebPanel-Core/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:87\nStack trace:\n#0 /var/www/shop/WebPanel-Core/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(88): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /var/www/shop/WebPanel-Core/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\\Handler\\RotatingFileHandler->write(Array)\n#2 /var/www/shop/WebPanel-Core/vendor/monolog/monolog/src/Monolog/Logger.php(289): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#3 /var/www/shop/WebPanel-Core/vendor/monolog/monolog/src/Monolog/Logger.php(565): Monolog\\Logger->addRecord(400, Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException), Array)\n#4 /var/www/shop/WebPanel-Core/vendor/laravel/framework/src/Illuminate/Log/Wri in /var/www/shop/WebPanel-Core/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 87

**Comment by Arrow768** [comment]
Issue with the permissions of the file / directory

**Comment by cruderustle** [comment]
@Arrow768 What permissions are necessary and on which files?
